devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls")),
    path("projects/", include("projects.urls")),
    path(
        "reset_password", auth_views.PasswordResetView.as_view(template_name='reset_password.html'), name="reset_password"
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(template_name='password_sent.html'),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(template_name='confirm_password.html'),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),

    path('', views.profiles, name='profiles' ),
    path('user-profile/<str:pk>/', views.user_profile, name='user-profile'),
    path('account/', views.user_account, name='account'),
    path('edit-profile/', views.edit_profile, name='edit-profile'),

    path('create-skill/', views.create_skill, name='create-skill'),
    path('update-skill/<str:pk>/', views.update_skill, name='update-skill'),
    path('delete-skill/<str:pk>/', views.delete_skill, name='delete-skill'),

    path('inbox/', views.all_messages, name='inbox'),
    path('message/<str:pk>/', views.view_message, name='message'),
    path('add_message/<str:pk>/', views.add_message, name='add-message'),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile


class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField("Tag", blank=True)
    created = models.DateTimeField(auto_now_add=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ["-vote_ratio", "-vote_total", "title"]

    @property
    def image_url(self):  
        try:
            url = self.featured_image.url
        except:
            url = '/images/default.jpg'
        return url

    @property
    def get_vote_count(self):
        reviews = self.review_set.all()
        up_vote = reviews.filter(value='up').count()
        total_votes = reviews.count()
        if total_votes == 0:
            ratio = 0
        else:
            ratio = (up_vote/total_votes) * 100
        self.vote_total = total_votes
        self.vote_ratio = ratio
        self.save()

    @property
    def reviewers(self):
        query_set = self.review_set.all().values_list('owner__id', flat=True)
        return query_set

class Review(models.Model):
    VOTE_TYPE = (("up", "Vote up"), ("down", "Vote down"))
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, primary_key=True, editable=False, unique=True
    )

    class Meta:
        unique_together = [['owner', 'project']]

    def __str__(self) -> str:
        return self.value
    

class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, primary_key=True, editable=False, unique=True
    )

    def __str__(self) -> str:
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=300, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(
        blank=True,
        null=True,
        upload_to="profiles/",
        default="profiles/user-default.png",
    )
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkdin = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, editable=False, primary_key=True
    )

    def __str__(self):
        return str(self.user.username)
    
    class Meta:
        ordering = ['created']


class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, editable=False, primary_key=True
    )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)

class Message(models.Model):
    sender = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True
    )
    recipient = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name='messages'
    )
    name = models.CharField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    is_read = models.BooleanField(default=False, null=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self):
        return self.subject
    
    class Meta:
        ordering = ['is_read', '-created']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Skill, Message


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["first_name", "username", "email", "password1", "password2"]
        labels = {"first_name": "Name"}
    def __init__(self, *args, **kwargs) -> None:
        super(UserForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            "name",
            "email",
            "username",
            "location",
            "bio",
            "short_intro",
            "profile_image",
            "social_github",
            "social_linkdin",
            "social_youtube",
            "social_twitter",
        ]

    def __init__(self, *args, **kwargs) -> None:
        super(ProfileForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})


class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = ['name', 'description']

    def __init__(self, *args, **kwargs) -> None:
        super(SkillForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']

    def __init__(self, *args, **kwargs) -> None:
        super(MessageForm, self).__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs.update({"class": "input"})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import User, Profile, Message
from .forms import UserForm, ProfileForm, SkillForm, MessageForm
from .utils import profile_search, custom_paginator

def register_user(request):
    page = "register"
    form = UserForm()
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request, "You are successfully registered")
            login(request, user)
            return redirect("edit-profile")
        else:
            messages.error(request, "An error occurred during registration")
    context = {"page": page, "form": form}
    return render(request, "users/login.html", context)


def login_user(request):
    page = "login"
    if request.user.is_authenticated:
        return redirect("profiles")

    if request.method == "POST":
        username = request.POST["username"].lower()
        password = request.POST["password"]

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, "User doesn't exist")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(request.GET['next'] if 'next' in request.GET else "account")
        else:
            messages.error(request, "Username OR Password is incorrect")
    context = {}
    return render(request, "users/login.html", context)


def logout_user(request):
    logout(request)
    messages.success(request, "User was successfully logout")
    return redirect("profiles")


def profiles(request):
    search, profiles = profile_search(request)
    profiles, custom_range = custom_paginator(request, profiles, 6)
    context = {"profiles": profiles, "search": search, 'custom_range': custom_range}
    return render(request, "users/profiles.html", context)


def user_profile(request, pk):
    profile = Profile.objects.get(id=pk)
    top_skills = profile.skill_set.exclude(description__exact="")
    other_skills = profile.skill_set.filter(description="")
    context = {
        "profile": profile,
        "top_skills": top_skills,
        "other_skills": other_skills,
    }
    return render(request, "users/user-profile.html", context)


@login_required(login_url="login")
def user_account(request):
    profile = request.user.profile
    context = {"profile": profile}
    return render(request, "users/account.html", context)


@login_required(login_url="login")
def edit_profile(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        form.save()
        return redirect("account")
    context = {"form": form}
    return render(request, "users/profile_form.html", context)


@login_required(login_url="login")
def create_skill(request):
    profile = request.user.profile
    form = SkillForm()
    if request.method == "POST":
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner = profile
            skill.save()
            messages.success(request, "Skill was added successfully!")
            return redirect("account")
    context = {"form": form}
    return render(request, "users/skill_form.html", context)


@login_required(login_url="login")
def update_skill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)
    form = SkillForm(instance=skill)
    if request.method == "POST":
        form = SkillForm(request.POST, instance=skill)
        if form.is_valid():
            form.save()
            return redirect("account")
    context = {"form": form}
    return render(request, "users/skill_form.html", context)


@login_required(login_url="login")
def delete_skill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)
    obj = skill.name
    if request.method == "POST":
        skill.delete()
        messages.success(request, "Skill was deleted successfully.")
        return redirect("account")
    return render(request, "delete_form.html", {"obj": obj})

@login_required(login_url="login")
def all_messages(request):
    profile = request.user.profile
    message_requests = profile.messages.all()
    unread_count = message_requests.filter(is_read=False).count()
    context = {'message_requests': message_requests, 'unread_count': unread_count}
    return render(request, 'users/inbox.html', context)

@login_required(login_url="login")
def view_message(request, pk):
    profile = request.user.profile
    request_message = profile.messages.get(id=pk)
    if request_message.is_read == False:
        request_message.is_read = True
        request_message.save()
    context = {'request_message': request_message}
    return render(request, 'users/message.html', context)


def add_message(request, pk):
    form = MessageForm()
    recipient = Profile.objects.get(id=pk)
    try:
        sender = request.user.profile
    except:
        sender = None

    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            new_message = form.save(commit=False)
            new_message.sender = sender
            new_message.recipient = recipient

            if sender:
                new_message.name = sender.name
                new_message.email = sender.email
            new_message.save()

            messages.success(request, 'Your message was sent successfully!')
            return redirect('user-profile', pk=recipient.id)
    context = {'form': form, 'recipient': recipient}
    return render(request, 'users/message_form.html', context)

users/templates/users/account.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-profile' %}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">{{profile.location}}</p>
              <ul class="dev__social">
                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i>Github</a>
                </li>
                {%endif%}
                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i>Twitter</a>
                </li>
                {%endif%}
                {% if profile.social_linkdin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkdin}}" target="_blank"><i class="im im-linkedin"></i>LinkedIn</a>
                </li>
                {%endif%}
                {% if profile.social_youtube %}
                <li>
                  <a title="YouTube" href="{{profile.social_youtube}}" target="_blank"><i class="im im-globe"></i>YouTube</a>
                </li>
                {%endif%}
              </ul>
              <a href="" class="btn btn--sub btn--lg">Send Message</a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-skill' %}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
            {% for skill in profile.skill_set.all %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{skill.name}}</h4>
                <p>
                 {{skill.description}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' skill.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
                </td>
              </tr>
              {% endfor %}
          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">
            {% for project in profile.project_set.all %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'single-project' project.id %}"><img src="{{project.image_url}}" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'single-project' project.id %}">{{project.title}}</a>
                <p>
                  {{project.description|slice:"150"}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-project' project.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="#"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}

          </table>
        </div>
      </div>
    </div>
  </main>

  {% endblock %}

users/templates/users/inbox.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
  <!-- Main Section -->
  <main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{unread_count}}</span>)</h3>
      <ul class="messages">
        {% for message in message_requests %}
        <li class="message {% if message.is_read == False %} message--unread {% endif %}">
          <a href="{% url 'message' message.id %}">
            <span class="message__author">{{message.name}}</span>
            <span class="message__subject">{{message.subject}}</span>
            <span class="message__date">{{message.created}}</span>
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </main>

{% endblock %}

users/templates/users/login.html
{% extends 'main.html' %}
 {% block content %} 
 {% load static %}
  {% if page == 'register' %}

<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{% static 'images/icon.svg' %}" alt="icon" />
      </a>
      <h3>Account SignUp</h3>
      <p>Create a new developer account</p>
    </div>

    <form action="{% url 'register' %}" method="post" class="form auth__form">
      <!-- Input:Text -->
      {%csrf_token%} {% for field in form %}
      <div class="form__field">
        <label for="">{{field.label}}</label>
        {{field}}

        {% for error in field.errors %}
        <p style="color: red;">{{error}}</p>
        {% endfor %}

      </div>
      {% endfor %}
      <div class="auth__actions">
        <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
      </div>
    </form>
    <div class="auth__alternative">
      <p>Already have an Account?</p>
      <a href="{% url 'login' %}">Log In</a>
    </div>
  </div>
</div>

{% else %}

<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{% static 'images/icon.svg' %}" alt="icon" />
      </a>
      <h3>Account Login</h3>
      <p>Hello Developer, Welcome Back!</p>
    </div>

    <form action="" method="post" class="form auth__form">
      {%csrf_token%}

      <!-- Input:Email -->
      <div class="form__field">
        <label for="formInput#text">Username: </label>
        <input
          class="input input--text"
          id="formInput#text"
          type="text"
          name="username"
          placeholder="Enter your username..."
        />
      </div>

      <!-- Input:Password -->
      <div class="form__field">
        <label for="formInput#password">Password: </label>
        <input
          class="input input--password"
          id="formInput#passowrd"
          type="password"
          name="password"
          placeholder="password"
        />
      </div>
      <div class="auth__actions">
        <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
        <a href="{% url 'reset_password' %}">Forget Password?</a>
      </div>
    </form>

    <div class="auth__alternative">
      <p>Don’t have an Account?</p>
      <a href="{% url 'register' %}">Sign Up</a>
    </div>
  </div>
</div>

{% endif %} 
{% endblock %}

users/templates/users/message.html
{% extends 'main.html' %}
{% block content %}
  <!-- Main Section -->
  <main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{% url 'inbox' %}"><i class="im im-angle-left"><</i></a>
        <h2 class="message__subject">{{request_message.subject}}</h4>
          {% if request_message.sender  %}
          <a href="{% url 'user-profile' request_message.sender.id %}" class="message__author">{{request_message.name}}</a>
          {% else %}
          <p class="message__author">{{request_message.name}}</>
          {% endif %}
          <p class="message__date">{{request_message.created}}</p>
          <div class="message__body">
            {{request_message.body|linebreaksbr}}
          </div>
      </div>
    </div>
  </main>

{% endblock %}

users/templates/users/message_form.html
{% extends 'main.html' %}
{% block content %}
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'user-profile' recipient.id %}"><i class="im im-angle-left"></i><</a>
            <br>
            <form class="form" action="" method="post">
                <!-- Input:Text -->
                {%csrf_token%}
                {% if request.user.is_authenticated == False %}
                <div class="form__field">
                    <label for="formInput#text">{{form.name.label}}</label>
                    {{form.name}}
                </div>
                <div class="form__field">
                    <label for="formInput#text">{{form.email.label}}</label>
                    {{form.email}}
                </div>
                {% endif %}
                <div class="form__field">
                    <label for="formInput#text">{{form.subject.label}}</label>
                    {{form.subject}}
                </div>
                <div class="form__field">
                    <label for="formInput#text">{{form.body.label}}</label>
                    {{form.body}}
                </div>
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
        </div>
    </main>
{% endblock %}

users/templates/users/profile_form.html
{% extends 'main.html' %}
{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i><</a>
            <br>

            <form class="form" action="" method="post" enctype="multipart/form-data">
                <!-- Input:Text -->
                {%csrf_token%}
                {% for field in form %}
                <div class="form__field">
                    <label for="formInput#text">{{field.label}}</label>
                        {{field}}
                </div>
                {% endfor %}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
        </div>
    </main>
{% endblock  %}

users/templates/users/skill_form.html
{% extends 'main.html' %}
{% block content %}
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i><</a>
            <br>

            <form class="form" action="" method="post">
                <!-- Input:Text -->
                {%csrf_token%}
                {% for field in form %}
                <div class="form__field">
                    <label for="formInput#text">{{field.label}}</label>
                        {{field}}
                </div>
                {% endfor %}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
        </div>
    </main>
{% endblock %}

users/templates/users/user-profile.html
{% extends 'main.html' %}
{%block content%}
  <!-- Main Section -->
  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">{{profile.location}}</p>
              <ul class="dev__social">
                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i>Github</a>
                </li>
                {%endif%}
                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i>Twitter</a>
                </li>
                {%endif%}
                {% if profile.social_linkdin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkdin}}" target="_blank"><i class="im im-linkedin"></i>LinkedIn</a>
                </li>
                {%endif%}
                {% if profile.social_youtube %}
                <li>
                  <a title="YouTube" href="{{profile.social_youtube}}" target="_blank"><i class="im im-globe"></i>YouTube</a>
                </li>
                {%endif%}
              </ul>
              {% if request.user.profile.id != profile.id %}
              <a href="{% url 'add-message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
              {% for skill in top_skills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{skill}}</h4>
                <p class="devSkill__info">
                  {{skill.description}}
                </p>
              </div>
              {% endfor %}
              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
              {% for skill in other_skills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{skill.name}}</small>
                </span>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">
              {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'single-project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{project.image_url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href="{% url 'user-profile' project.owner.id %}">By {{project.owner}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                        Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag.name}}</small>
                        </span>
                        {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {%endfor%}
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{%endblock%}